### PR TITLE
Makes conversion work also on the iOS

### PR DESCRIPTION
**Pull request by bazinac**

### CODE REVIEW

**Comment by am15h** [comment]
@bazinac Thanks a lot for your pull request.

**Comment by tomk9** [comment]
@bazinac I tested your PR and bounding boxed are shifted on iOS.
| Android | iOS |
| --- | --- |
| Screenshot_20201217-190806 | IMG_0564 |

**Comment by tomk9** [comment]
Probably my problem with iOS is caused by this statement https://github.com/am15h/object_detection_flutter/blob/a5281e11b885a57e9ee2a2c7cc162a95554caed1/lib/ui/camera_view.dart#L92
So it is not in the scope of PR. @am15h please merge this PR.

**Review by tomk9 — APPROVED** [review]

**Comment by am15h** [comment]
Thanks, @bazinac, and @tomk9 for your kind efforts. Very sorry for the delay, I was unable to get my hands on an iOS device for testing this. 

The shifting of bounding boxes needs to be investigated separately.

**Pull request merged**
